### ISSUE TITLE
Updates once we have a Helidon release with #135 fixed

### ISSUE THREAD

**Issue by batsatt** [oracle/helidon-build-tools#109]
Once we have the new archetype mechanism is in place, and we configure the helidon-maven-plugin as required in #135, **_and_** there has been a helidon release containing it, do the following:

- set `CommandAssertions.MINIMUM_HELIDON_VERSION` to the release version
- remove precondition in `CommandTest`
- remove try/catch in `AppTypeBrowserTest`

**Comment by barchetta** [comment]
Proposal is to silently release a Helidon-M4 that contains #134 and #135
