### ISSUE TITLE
Build a native image for windows CLI

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon-build-tools#120]
- [x] Investigate if we need to sign the binary. (moved to https://github.com/oracle/helidon-build-tools/issues/120)

**Comment by hantsy** [comment]
Or adding an installation into SDKMan, like what's done in Micronaunt.

https://docs.micronaut.io/1.1.x/guide/index.html#installSdkman

**Comment by romain-grecourt** [comment]
SDKMan is more like a package manager, this is a separate issue. We should probably also support homebrew, chocolatey etc.

**Comment by romain-grecourt** [comment]
See #250 #254

**Comment by romain-grecourt** [comment]
Created a new issue to track signatures (https://github.com/oracle/helidon-build-tools/issues/120).
