### ISSUE TITLE
Detect proxy from environment in the CLI

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-build-tools#125]
Add support for http_proxy HTTP_PROXY https_proxy HTTPS_PROXY noproxy NOPROXY no_proxy and NO_PROXY in the CLI.

Add sort-of hidden options for these (something that can also be set in the user preferences file if we have one).

Decide how to handle noproxy NOPROXY no_proxy and NO_PROXY when converting these to `-Dhttp.nonProxyHost`.

**Comment by batsatt** [comment]
fixed by PR #153
