### ISSUE TITLE
Decide where dev extension should be configured and get it into Helidon

### ISSUE THREAD

**Issue by batsatt** [oracle/helidon-build-tools#135]
For the dev command to function, we need to ensure the following property is present:
```
<version.helidon.plugin>XX</version.helidon.plugin>
```
as well as this plugin declaration:
```
<plugin>
    <groupId>io.helidon.build-tools</groupId>
    <artifactId>helidon-maven-plugin</artifactId>
    <version>${version.helidon.plugin}</version>
    <extensions>true</extensions>
</plugin>
```

We had discussed putting this in the application parent pom rather than embedding it in the new archetype templates. However, this makes it more difficult for the CLI to configure the plugin version, since it is not part of the templates.

**Comment by romain-grecourt** [comment]
Why do we need to explicitly configure the plugin version ?
It can (should?) just be derived from the application parent pom.

If we have a way to pass properties to the forked maven command, it can be used to override `version.helidon.plugin`.

Also, deriving the plugin version used by the CLI directly from the application pom would allow us to deliver bug fixes for the plugins without necessarily having to publish a new CLI version.

**Comment by batsatt** [comment]
I think `helidon init` should be able to select the plugin version, rather than have it bound to the Helidon version from which the parent pom comes.
 
The case I was thinking about is when we have more than one 2.x release (e.g. 2.0.0, 2.1.0), and a new CLI release (e.g. 2.1.0 if was tracking helidon releases). If you then use the 2.1.0 CLI and select an _older_ version of helidon:
```
    helidon init --version 2.0.0
```
what version of the plugin should be configured in the app? I think the default behavior should be that you end up with 2.1.0 rather than 2.0.0. If the actual version used comes from our new metadata file, we can deliver plugin fixes that way.

And yes, we could _temporarily_ change the version when under the CLI by passing the property, but that disappears when `mvn` is used directly.

**Comment by romain-grecourt** [comment]
If we include the latest plugin version in the new metadata file, then that works.
I'm not sure I understand your last point ; if `mvn` is invoked directly the CLI is not involved right ?

**Comment by batsatt** [comment]
Right, and so any "update" of the plugin version via the property would not (automatically) be in effect. I don't think we want different plugin versions depending on how you do the build. 

We should select the plugin version during `init` and expand the template such that this version is used.

For other commands that do builds, if we get metadata that says there is a newer plugin version, we could ask the user if we can update the app pom with the new version.

All of this suggests to me that we have to be able to control the plugin version in the app pom, not the parent.
