### ISSUE TITLE
Be able to run CLI binary against staged artifacts

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon-build-tools#160]
Provide a way to override the value of:

```
public static final URI DEFAULT_REPOSITORY_URI = toUri("https://repo.maven.apache.org/maven2/");
```
So that you can test a CLI binary against a staged Helidon release (in `https://oss.sonatype.org/content/groups/staging`);

**Comment by batsatt** [comment]
Fixed by #182 
The `init` command supports an undocumented `--url` argument.
