### ISSUE TITLE
Would be nice to be able to use Java debugger with server run by CLI dev loop

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon-build-tools#173]
It would be nice to be able to have the dev loop start the server with debugging enabled.

**Comment by romain-grecourt** [comment]
There is a way, but it's not documented.
See https://github.com/oracle/helidon-build-tools/blob/d5221ef394c21a786490932e07fd4905bbb893ee/helidon-cli/impl/helidon.sh#L30

We should discuss the possibility of adding proper cli options to support this.

**Comment by romain-grecourt** [comment]
With #248 it will be possible to pass `-Dmaven.debug.port` or `-Dmaven.child.debug.port` with the native executable.
Currently the only way is to set the `MAVEN_DEBUG_OPTS` environment variable.

@batsatt we need to decide if we want to map a cli options for attaching the debugger or if we leave it with the current properties.

**Comment by batsatt** [comment]
Closed by #306.
