### ISSUE TITLE
Out of sync project config when pom is updated manually

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-build-tools#204]
The project config may be out of sync when the pom.xml file is updated manually.
E.g. one bumps the helidon application parent pom manually.

We need a way to invalidate the project config and synchronize it with the pom.xml

**Comment by romain-grecourt** [comment]
Current workaround is to manually delete the project config file `project/.helidon`.

**Comment by batsatt** [comment]
@romain-grecourt I think this may be covered already, now that the dev extension adds the helidon version.

**Comment by romain-grecourt** [comment]
This needs to be verified against 2.x as well.

**Comment by batsatt** [comment]
I've verified that changing the parent pom version is detected correctly under both 2.x and 3.0.0-SNAPSHOT, in both scenarios:

1. change is made while dev loop running: change is detected and rebuild occurs.
2. change is made while dev loop is not running: change is detected on dev loop start and rebuild occurs.

Was there some other condition you were concerned about?

**Comment by romain-grecourt** [comment]
I think that was it.
