### ISSUE TITLE
CLI doesn't exit when port is already used. 

### ISSUE THREAD

**Issue by delabassee** [oracle/helidon-build-tools#222]
If the port is already used, the CLI will rightly throw `Caused by: java.net.BindException: Address already in use` but it'll wait instead of quitting.

**Comment by batsatt** [comment]
I assume you're talking about `helidon dev`. If so, I cannot reproduce this; the error message/trace is logged in red and the CLI exits. 

The code is currently very generic (and dumb, unfortunately), exiting if it sees _any_ output on `stderr` from the application. In my env, at least, this works for the code generated by the new archetypes.

Please provide steps to reproduce if you can.

**Comment by spericas** [comment]
I have tried this with one of our archetypes. Executed app in background and then started dev loop. An exception was thrown but _the command exited_ for me.

**Comment by batsatt** [comment]
@delabassee Can you provide steps to reproduce?

**Comment by delabassee** [comment]
I tried but I can't reproduce!
I was using, I think some MS build for the CLI.
