### ISSUE TITLE
RFE: 'cli dev' should support an optional project directory 

### ISSUE THREAD

**Issue by delabassee** [oracle/helidon-build-tools#238]
Right now, one should be in the project directory before running `helidon dev`.

It would make sense to also allow specifying the project dir as an argument, i.e. `helidon dev ~/myProjectDirectory`. This would mimic the usual behaviour of Go based tools.

**Comment by batsatt** [comment]
We do support this via the `--project` option; however, I do like the simpler, more direct variant. Will take a look at supporting this.
