### ISSUE TITLE
RFE: pass arguments when using 'helidon dev'

### ISSUE THREAD

**Issue by delabassee** [oracle/helidon-build-tools#239]
When trying the use JDK 15 preview features, I bumped into the following limitation using the `dev` mode (or I haven't looked hard enough).

In `dev` mode, it should be possible to pass arguments,
* to the compiler (possible via the pom.xml)
* to the JVM that will run the App.

**Comment by romain-grecourt** [comment]
see https://github.com/oracle/helidon-build-tools/issues/245

**Comment by batsatt** [comment]
@delabassee Do you actually need to pass _compiler_ arguments on the command line for some reason? We directly use the maven compile goal in the dev loop, so the most we could do is pass properties to maven; is there some use case where modifying the plugin configuration in the pom is not sufficient?

**Comment by delabassee** [comment]
@batsatt in my uses, i.e. preview features, I need to pass to java `--enable-preview --release xx` (xx being the Java version)

**Comment by batsatt** [comment]
Right, those are JVM options, not compiler options, and can now be passed (well, once we've released) like so:
```
--app-jvm-args "--enable-preview --release xx"
```
So... no need for compiler options on the `helidon dev` command line then, right?

**Comment by batsatt** [comment]
Oh, sorry, I see that you _also_ need those args to javac, but you should be able to configure that in the pom.

**Comment by delabassee** [comment]
no, we need to tell javac to enable preview features on the generated byte code using those 2 params. To use that byte code, we then need to tell hotspot using one single arg: "--enable-preview"

**Comment by delabassee** [comment]
see https://blogs.oracle.com/javamagazine/the-role-of-preview-features-in-java-14-java-15-java-16-and-beyond

**Comment by batsatt** [comment]
Right, as I said in the follow up comment, you can configure the pom for javac.

**Comment by delabassee** [comment]
Got it. That's what I currently do, to me it's fine.

**Comment by batsatt** [comment]
OK, great, then I'll close this.
