### ISSUE TITLE
add support for jlink-image to be able to add custom modules

### ISSUE THREAD

**Issue by bhushan2901** [oracle/helidon-build-tools#258]
As not all jars are converted to modules there is some requirement to add custom modules to be added if the current project does not have module-info.class ( as converting this will be a huge activity ) . 

if we have a way to add such custom modules via pom.xml it will make it easy for migrating from older versions.

**Comment by batsatt** [comment]
Jars without `module-info.class` are already supported. The output of `jllink-image` is a JRI containing only those JDK modules required by application: the application jars and dependencies are copied into the image _separately_ and are not included when `jlink` is run. Only the required JDK modules are passed to `jlink`.

The JDK dependencies are discovered using the `module-info.class` when present or the `jdeps` tool when missing. It is the latter case that I think you are concerned about? 

Or have you run into a situation where `jlink-image` fails?

**Comment by bhushan2901** [comment]
Hi 
Yes i am facing an issue where jlink-image fails. 
i am using jlink with jdk11 the code works fine without it but with jlink-image i get "Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure" while communicating with kubernetes .. I am suspecting this could be because of missing jdk.crypto.ec but not sure . ( I havent converted our project to modules yet so relying on the jdeps to get list of modules )

**Comment by batsatt** [comment]
I'd like to understand what you mean by "using jlink with jdk11". Since you haven't converted fully to modules, and `jlink` does not support automatic modules, I don't understand how it could work for your application. What exactly are you doing with `jlink` where it works fine?

**Comment by batsatt** [comment]
After some offline discussion, it seems to have been a Dockerfile issue.
