### ISSUE TITLE
Support backward compatibility with new cli maven plugin

### ISSUE THREAD

**Issue by batsatt** [oracle/helidon-build-tools#259]
Moving `helidon:dev` to `helidon-cli:dev` (issue #247) will break older CLI versions (`< 2.0.3`).
 Older CLI that refresh their metadata should not use the newest version of `helidon-maven-plugin`,
 otherwise invocations of `helidon:dev` will fail.

In order to fix the version of `helidon-maven-plugin` for older versions of the CLI, we will
 update the metadata to deprecate `build-tools.version` and introduce a new property `cli.{version}.plugin.version`.

The value of `build-tools.version` will remain untouched and contain the current version of `helidon-maven-plugin`.

The new property `cli.{version}.plugin.version` will drive the version of the new `helidon-cli-maven-plugin`, contains
 the lower bracket of the CLI version range that should use a specific version of the plugin.

```properties
# This is used by helidon cli <= 2.0.2
build-tools.version=2.0.2

# Version of the helidon-cli-maven-plugin by cli versions
# This allows to introduce backward incompatible changes in the helidon-cli-maven-plugin
cli.latest.plugin.version=2.2.0
cli.2.1.0.plugin.version=2.0.9
cli.2.0.3.plugin.version=2.0.3

# cli v2.0.1 -> helidon-maven-plugin v2.0.2
# cli v2.0.2 -> helidon-maven-plugin v2.0.2
# cli v2.0.3 -> helidon-cli-maven-plugin v2.0.3
# cli v2.0.4 -> helidon-cli-maven-plugin v2.0.3
# cli v2.0.5 -> helidon-cli-maven-plugin v2.0.3
# cli v2.1.0 -> helidon-cli-maven-plugin v2.0.9
# cli v2.1.1 -> helidon-cli-maven-plugin v2.0.9
# cli v2.1.2 -> helidon-cli-maven-plugin v2.0.9
# cli v2.2.0 -> helidon-cli-maven-plugin v2.2.0
```

**Comment by batsatt** [comment]
@romain-grecourt  Existing applications that want to use the new CLI features (e.g. `helidon dev --app-jvm-args "..."`) will need to update their pom to use the latest parent to get the new plugin. This is also the case for new applications where an older Helidon version is used during `init`.

We need some way to manage this, but no matter what we do it is a bit ugly, since at minimum it means that users are forced to a new Helidon version just to get a new CLI feature.

First, we can make the `dev` command determine which parent pom version is in use. Then... 

We could select the either the `helidon:dev` or `helidon-cli:dev` goal based on the parent version. However, this only works if we leave the existing `DevMojo` in place and no new feature is required (e.g. neither `--app-jvm-args` nor `--app-args`), so we'd need to be (forever?) on the hook to track options that require new features and:

1. Fail with a message telling them they need to update their pom to use the feature.
2. Ask if they want their pom updated and do it for them, then continue.  

In addition to keeping the existing `DevMojo` and tracking future new options, we would also need to continue to update `build-tools.version` to pick up bug fixes in the dev loop implementation. 

Alternatively, we could just unconditionally do 1 or 2 if an older parent pom is in use with the `dev` command, forcing them to a new Helidon version. This approach allows us to remove the old `DevMojo`, at the cost of potentially annoying our users or even breaking their app.

**Comment by romain-grecourt** [comment]
Here is some notes from the discussion between @batsatt and I.

## new CLI with old Helidon version

- Only helidon-maven-plugin is configured in the project model

```xml
    <profiles>
        <profile>
            <id>helidon-cli</id>
            <activation>
                <property>
                    <name>helidon.cli</name>
                    <value>true</value>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.helidon.build-tools</groupId>
                        <artifactId>helidon-maven-plugin</artifactId>
                        <version>${version.plugin.helidon}</version>
                        <extensions>true</extensions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

 - `helidon-cli:dev` does not work
 - `io.helidon.build-tools:helidon-cli-maven-plugin:2.1.0:dev` works

I.e the new CLI (v2.1.0) should invoke the plugin using fully qualified notation

## Old CLI with new Helidon version

- Both plugins configured in the project model
- Only new plugin configured as an extension

```
  <build>
      <pluginManagement>
          <plugins>
              <plugin>
                  <groupId>io.helidon.build-tools</groupId>
                  <artifactId>helidon-maven-plugin</artifactId>
                  <version>${version.plugin.helidon}</version>
              </plugin>
              <plugin>
                  <groupId>io.helidon.build-tools</groupId>
                  <artifactId>helidon-cli-maven-plugin</artifactId>
                  <version>${version.plugin.helidon-cli}</version>
              </plugin>
          </plugins>
      <pluginManagement>
  </build>
  <profiles>
      <profile>
          <id>helidon-cli</id>
          <activation>
              <property>
                  <name>helidon.cli</name>
                  <value>true</value>
              </property>
          </activation>
          <build>
              <plugins>
                  <plugin>
                      <groupId>io.helidon.build-tools</groupId>
                      <artifactId>helidon-cli-maven-plugin</artifactId>
                      <extensions>true</extensions>
                  </plugin>
              </plugins>
          </build>
      </profile>
  </profiles>
```

- `helidon:dev` does not work as-is (because helidon-maven-plugin:2.1.0 does not contain the dev goal anymore)
- `helidon:dev -Dversion.plugin.helidon=2.0.2` works (because metadata contains "build-tools.version=2.0.2")

No devloop bug fixes with old CLI, if you have a bug a `helidon dev`, you upgrade the cli to get a bugfix.
