### ISSUE TITLE
Provide a way to make a card clickable

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-build-tools#28]
There is currently no way to make a card clickable.

```
[CARD]
.Config
[icon=settings]
--
A flexible configuration framework with support for multiple sources and formats.
--
```

I'm thinking of adding an attribute link like below:

```
[CARD]
.Config
[icon=settings, link=config/08_supported-formats.adoc#Config-ModuleHocon]
--
A flexible configuration framework with support for multiple sources and formats.
--
```

**Comment by romain-grecourt** [comment]
@tjquinno let me know if you have some thoughts about this.

**Comment by tjquinno** [comment]
So this would make the _icon_ clickable, meaning anything we'd want clickable would need to have an icon?

Maybe that's fine, but:
1. Do we want to impose that requirement for clickability?
2. If so, will we get bogged down in finding good icons for each item we want clickable?

**Comment by tjquinno** [comment]
I don't know my HTLM/CSS very well, but does the solution here help?
https://stackoverflow.com/questions/796087/make-a-div-into-a-link

**Comment by romain-grecourt** [comment]
sorry about the confusion, I'm thinking about making the card clickable with or without icons.

**Comment by romain-grecourt** [comment]
The link implementation needs to be done the same way as for other links. I'm looking at making the code for link a little better rather than duplicating what we have right now in 2 places.
