### ISSUE TITLE
devloop hangs if the app can't start

### ISSUE THREAD

**Issue by delabassee** [oracle/helidon-build-tools#284]
On 2.1.0
* Compile an application with preview features enabled
```
 <artifactId>maven-compiler-plugin</artifactId>
 <configuration>
    <compilerArgs>--enable-preview</compilerArgs>
     <release>15</release>
 </configuration>
```
* Run it `Helidon dev`

* It will hang given we didn't pass `--app-jvm-args "--enable-preview"`, the CLI will just say

```
| build completed (12.6 seconds)
| bare-se starting
```

**Comment by batsatt** [comment]
@delabassee The only way we know what is going on with the app is by what it logs; can you please provide that output? (I don't have the bandwidth where I am at the moment to download another JDK.)

Currently, for any output on `stderr`, we consider it a failure and stop the app, then wait for changes and retry. We pass through anything on `stdout`. 

We'd need to special case this particular error and exit the loop so you can pass the arguments.

**Comment by delabassee** [comment]
@batsatt The following is sent to `stderr`
```
Error: LinkageError occurred while loading main class com.devlive.Main
	java.lang.UnsupportedClassVersionError: Preview features are not enabled for com/devlive/Main (class file version 59.65535). Try running with '--enable-preview'
```

**Comment by delabassee** [comment]
hmm, shouldn't this fail properly given that this error is sent on `stderr` ?

**Comment by batsatt** [comment]
It should, yes, on the current CLI version. The next release will not exit the loop on `stderr` output except for special cases, and this one is easy enough to handle. I'll see if I can reproduce this.

**Comment by batsatt** [comment]
I have a fix for this, but it is dependent on another fix in the works; will be available in the next release though.
