### ISSUE TITLE
Dev loop stops on invalid application.yaml

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon-build-tools#286]
When I broke the `application.yaml` in Helidon SE, the dev loop exited (I got the exception that the yaml is not valid).

How to break it:
```
app.greeting="Hello"
```
should be:
```
app.greeting: "Hello"
```

I think the dev loop should report the error, but not quit.

Version: 2.0.2 of Helidon and 2.1.0 of build tools

**Comment by romain-grecourt** [comment]
When I make the change above, it does not generate a YAML parser exception. However, if I simply add a new line with "xxx" it reproduces the issue.
