### ISSUE TITLE
helidon init project directory is very surprising when not specified

### ISSUE THREAD

**Issue by batsatt** [oracle/helidon-build-tools#326]
When not specified, the project directory is set to the current working directory, as it always has been. However, a recent change uses this directory instead of trying a subdirectory using the provided (or input from prompt) name.

This change means that the test to ensure the directory does not already exist will *always* fail, and the previous logic to generate a unique name was not updated. Since that code assumed the project directory was a subdirectory, it backs up to the parent and regenerates a name.

The net effect is that `helidon init` creates a project in the *parent* of the current directory, which definitely violates the principle of least surprise.

Further, if the project directory _is_ specified, the result is also very confusing if the directory already exists. If, e.g., a directory called `foo` exists in the current working directory, `helidon init --project foo` will use the project name when generating alternatives to find an unused directory. 

Both of these behaviors are confusing and need to be fixed before the next release.

**Comment by batsatt** [comment]
Seems to me that we should do the following...

If the project directory is NOT specified via `--project`:

- Use **project name** as subdirectory (as before), or variations if already exists.

If the project directory IS specified via `--project`:

- if the directory does not exist, use it, else
- generate variations of the **directory name**

@romain-grecourt and @barchetta: thoughts?

**Comment by romain-grecourt** [comment]
I agree with the first 2 points, however I think we might want to fail when the directory explicitly specified by the user already exists.

**Comment by batsatt** [comment]
Right, yes, that makes more sense.
