### ISSUE TITLE
Property not passed through all the way

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-build-tools#332]
When passing `-Dmaven.repo.local` to the helidon-cli with a fresh repository, some of the output is not filtered.
It seems this indicates that the property is not passed through on some of the Maven invocation(s).

Steps to reproduce:
```
mv ~/.m2/repository/io/helidon ~/.m2/repository/io/helidon.bck
rm -rf /tmp/repo
helidon dev -Dmaven.repo.local=/tmp/repo
```

This happens with all variants of the cli (native, plain etc.)

**Comment by batsatt** [comment]
This can be reproduced with the local snapshot build using the following to execute `helidon dev`:
```
rm -rf /tmp/repo && \
mkdir -p /tmp/repo/io/helidon/ && \
cp -r ~/.m2/repository/io/helidon/build-tools/ /tmp/repo/io/helidon/build-tools/ && \
helidon dev --clean -Dmaven.repo.local=/tmp/repo --current
```
Passing the `maven.repo.local` property through does not fix the issue. It is likely this is just a more complex case for `DevCommand.TerminalModeOutput` to handle; I will look at this next.

**Comment by batsatt** [comment]
Download progress output occurs during the application build phase because the repo starts off empty and our plugin dependencies still need to be resolved. `DevCommand.TerminalModeOutput` has been updated to suppress these messages during the build.
