### ISSUE TITLE
JLink start command changes current directory

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon-build-tools#334]
The program should run from the directory of the user, not from the JRI directory.

When I start the program, for example in `/home/me`, I expect the `user.dir` to be `/home/me`, but it changes to the JRI directory, such as `/home/me/my-app-jri`.

This causes issues with any use of relative directories in the application.

**Comment by batsatt** [comment]
@tomas-langer As I thought, I did do this deliberately: it is a requirement to make CDS work. 

The CDS archive is a cache, so the JVM has to validate it against the classpath. Unfortunately, it is not very flexible when it comes to file system paths, the best you can do is ensure that they are _relative_ to the JRI directory, hence the `cd` in the start script. Without that, CDS will fail:
```
        Error occurred during initialization of VM
        An error has occurred while processing the shared archive file.
        Unable to use shared archive.
        shared class paths mismatch (hint: enable -Xlog:class+path=info to diagnose the failure)
```
We can avoid the `cd` when CDS is disabled, though this could be a confusing/problematic difference in behavior. I will experiment with this approach.
