### ISSUE TITLE
Make maxWaitSeconds and maxAppStartSeconds in helidon-linker

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-build-tools#342]
jlink-image can fail with a time out. The time can vary from system to system and project to project.
It is currently hard-coded and should be made configuration.

Both of `maxWaitSeconds` and ``maxAppStartSeconds` should be configurable by either system property or plugin configuration.

**Comment by batsatt** [comment]
This was fixed some time ago.
