### ISSUE TITLE
Dev-loop double prime build when dependencies are resolved by the prime build

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-build-tools#414]
`Project.isBuildUpToDate()` has the following check:

```java
        // Are any dependencies newer than the most recent source?

        for (final BuildFile file : dependencies()) {
            final Optional<FileTime> changed = file.changedTimeIfOlderThan(latestBinary);
            if (changed.isPresent() && newerThan(changed.get(), latestSource)) {

                System.out.println("### dependencies newerThan ###" + file.path());
                // Yes, so we are not up to date.

                return false;
            }
        }
```

The jar files copied under `target/libs` as part of the prime builds have their timestamp identical to the original file in the local Maven repository. If the original file was resolved by Maven during the prime build itself, then the timestamp will be newer than the latest source file.

In other words, `Project.isBuildUpToDate()` will always return false if any of the project dependencies is resolved as part of the prime build.

This method is only used by test classes under, therefore the impact is unclear.

**Comment by batsatt** [comment]
I can't reproduce this, and I'm not sure how it could happen: the dev loop uses dependencies directly out of the local repo, and does not use `target/libs` at all. Deleting a dependency from the local repo does cause it to re-download during a full/prime build, of course, but then that new timestamp is stored for the next time we do a full build. 

Am I misunderstanding something?

**Comment by romain-grecourt** [comment]
This is about DefaultProjectSupplier which is only used as part of the tests.

For this to happen both `target/libs` and `package` phase need to be used and it's only the case for the tests that use DefaultProjectSupplier. I.e. it's a test issue only.

It looks like the failing tests this was reported on was `DefaultProjectSupplierTestIT.testUpToDate`, however this tests currently runs as expected. i.e it does not do another prime build.
