### ISSUE TITLE
Sometimes need to touch pom.xml twice for dev loop to process the change

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon-build-tools#429]
Helidon 2.3.0, CLI 2.2.0

Run `helidon init` and choose an MP quick-start app and choose to run the dev loop.

Open the new project in IntelliJ IDEA. 

1. Add this dependency to the pom:
```
<dependency>
    <groupId>io.helidon.integrations.micrometer</groupId>
    <artifactId>helidon-integrations-micrometer-cdi</artifactId>
</dependency>
```
2. Click the icon to update IntelliJ given the pom change. This also writes the file and the dev loop rebuilds and restarts the server.
3. Open `GreetResource.java` and insert
```
@Inject
private MeterRegistry meterRegistry;
```
IntelliJ will correctly find MeterRegistry in the Micrometer transitive dependency pulled in by the dependency you added earlier and fill it in as you type.
4. Save the file.
5. The dev loop reports 
```
| source file changed
| rebuilding (incremental)

COMPILATION ERROR : 
/Users/tjquinn/mic/j4c/demo/quickstart-mp/src/main/java/me/tjquinn/mp/quickstart/GreetResource.java:[20,37] package io.micrometer.core.instrument does not exist
/Users/tjquinn/mic/j4c/demo/quickstart-mp/src/main/java/me/tjquinn/mp/quickstart/GreetResource.java:[54,13] cannot find symbol
  symbol:   class MeterRegistry
  location: class me.tjquinn.mp.quickstart.GreetResource

| build failed
| waiting for source file changes
```
6. In the IDE, return to the `pom.xml`file and remove the earlier added space, or add a new space to the end of a line. Save the file.
7. The dev loop reports:
```
| build file changed
```
and then stalls.
6. Add a space to the pom again and save the file.
7. Now the dev loop sees and acts on the change, rebuilds with a _successful_ compilation this time, and all is well.

**Comment by tjquinno** [comment]
There are at least a couple of problems here:

1. The dev loop does not seem to learn, upon the first change to the `pom.xml` file, about the transitive dependency on the Micrometer artifact that the `helidon-integrations-micrometer-cdi` artifact brings with it. That would seem to cause the Java compilation error.
2. The dev loop stalls after I touched the `pom.xml` file after getting the compilation error.

**Comment by batsatt** [comment]
I was able to fix the "stall" issue, which was really a mistaken filtering of output rather than anything actually stalling.

I was able to reproduce the missing dependency issue, but only once: clearly some kind of race condition.

**Comment by batsatt** [comment]
The issue can be reproduced by executing the dev-loop using the `--clean` option. The fix is to share the `MavenSession` used during the full/prime build with the incremental build.
