### ISSUE TITLE
Expression Evaluator

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon-build-tools#434]
Implement https://github.com/oracle/helidon-build-tools/blob/master/docs-internal/archetype-v2.md#flow-context-path-expressions.

Initially implement a generic boolean expression evaluator with tests. Then add expressions that are specific to our spec.

**Comment by romain-grecourt** [comment]
Here is some work that I did some time ago for a pseudo expression language:

- https://github.com/romain-grecourt/helidon-build-tools/blob/userflow/userflow-maven-plugin/src/main/java/io/helidon/build/userflow/AbstratSyntaxTree.java
- https://github.com/romain-grecourt/helidon-build-tools/blob/userflow/userflow-maven-plugin/src/main/java/io/helidon/build/userflow/Expression.java
- https://github.com/romain-grecourt/helidon-build-tools/blob/userflow/userflow-maven-plugin/src/test/java/io/helidon/build/userflow/ExpressionTest.java
