### ISSUE TITLE
Maven plugins fail with Maven 3.8+ due to Jansi

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon-build-tools#458]
https://issues.apache.org/jira/browse/MNG-7223

Maven uses Jansi and upgraded to version 2.x in 3.8.1
As this seems to be part of our classloader, we are creating a conflict with the version used by Maven.
Even in 3.6, maven removes our Jansi dependency when creating classloader.

To work around this, we should not depend on Jansi at all in our Maven plugins, and should use the maven provided logging support.

**Comment by barchetta** [comment]
In terms of customer impact this breaks the `jlink-image` goal and `helidon dev`. The default build and native-image build seem to work OK.

**Comment by romain-grecourt** [comment]
This will need to be back-ported to the 2.x branch.

**Comment by barchetta** [comment]
I'm interested if there is a quick fix  that would allow the current code to run under Jansi 1.8 and 2.x. The use of `AnsiOutputStream` seems pretty limited in our code.
