### ISSUE TITLE
helidon dev doesn't notice Windows file updated

### ISSUE THREAD

**Issue by edbratt** [oracle/helidon-build-tools#483]
While working through the [Helidon / Verrazzano workshop](http://bit.ly/helidon-verrazzano-hol) using Windows PowerShell, helidon dev command doesn't notice that the file microprofile.config has been updated. Behavior is same for cmd and the latest 'Terminal' app for windows also.
Running Windows 10. JDK 17 and latest release of Helidon

> project.helidon.version  2.3.2
> project.flavor           MP
> latest.helidon.version   2.3.3

Note, I just invoke helidon dev in a Powershell terminal window. Not in an IDE.

**Comment by barchetta** [comment]
Could be same as  #357
