### ISSUE TITLE
Initial REST API implementation

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-build-tools#546]
Start a new (internal) repository that contains an Helidon application that implements the REST api for the starter website.

It should initially support one click links (e.g. `https://starter.helidon.io/api/v1/generate?flavor=se&media-support.json.provider=jackson`)

**Comment by tvallin** [comment]
Status: PR is created on internal repository

**Comment by tvallin** [comment]
Status : PR merged
