### ISSUE TITLE
Configurable metadata server URL

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon-build-tools#553]
The metadata server is currently hard-coded to point at `helidon.io`.

We currently have the `--url` option, but that’s only for the cli-data, we need a way to resolve cli metadata and cli-data against a different host.

We need a way to override the metadata server and have that used for resolving both the cli metadata and cli-data.
`--url` could still be passed and override the cli-data url since that's version specific.

It should be something like a `--metadata-host` option and logic in Metadata to use it.

**Comment by batsatt** [comment]
The metadata is stored inside of the cli-data zip files, so `--url` does work fine.
