### ISSUE TITLE
enforcer-maven-plugin does not handle MacOS case insensitive paths correctly

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon-build-tools#661]
While on MacOS I noticed the copyright check was passing even though it should have been failing. After some experimentation I determined it had to do with the MacOS case insensitive file system. Here is an example:

```
$ cd /Users/jdipol/GitHub/helidon-releases/helidon
$ etc/scripts/copyright.sh
[ERROR] webserver/webserver/pom.xml:4: Wrong year. Expected "2017, 2022", is "2017, 2021"
COPYRIGHT ERROR

$ cd /Users/jdipol/github/helidon-releases/helidon
$ etc/scripts/copyright.sh
COPYRIGHT OK
```

So when I used the proper mixed case directory it worked as expected. But if I used the case insensitive variant it did not work.

**Comment by barchetta** [comment]
Tim also reported this, so maybe we need to canonicalize filenames too?

I am renaming and editing a class from (for example) `OpenAPIMediaType` to `OpenApiMediaType`. But the copyright enforcer rule complains with this mysterious error:
-- enforcer results
error: Rule copyright failed. Errors:
error:   openapi/src/main/java/io/helidon/openapi/OpenAPIMediaType.java:2: Wrong year. Expected "2022, 2022", is "2022, 2023"

**Comment by ljnelson** [comment]
Related: https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/nio/file/Path.html#toRealPath(java.nio.file.LinkOption...)
