### ISSUE TITLE
ClassDataSharing does not work with Helidon 2.0.0-M1

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon-build-tools#67]
When I run tests, the `ClassDataSharingTest` gets stuck on:
```
Creating base image: target/helidon-quickstart-mp/target/mp-jri
Installing 156 application jars in target/helidon-quickstart-mp/target/mp-jri/app
  checking index in CDI beans archive helidon-quickstart-mp.jar
  creating missing index for CDI beans archive helidon-microprofile-server-2.0.0-M1.jar
  creating missing index for CDI beans archive jersey-weld2-se-2.29.1.jar
  creating missing index for CDI beans archive helidon-health-checks-2.0.0-M1.jar
  creating missing index for CDI beans archive helidon-microprofile-fault-tolerance-2.0.0-M1.jar
Creating startup class list for helidon-quickstart-mp.jar
```

I have added a workaround to `TestFiles` that limits the versions to 1.x (see line 184). If you revert this workaround to just look for latest version, it will fail (even local builds).

**Comment by tomas-langer** [comment]
This is most likely a two-fold bug
1. a bug in the implementation that does not timeout after a certain amount of time
2. a bug in Helidon that causes the situation to happen (maybe the exit on startup does not work as expected?)

**Comment by batsatt** [comment]
`ClassDataSharing` uses the `-Dexit.on.started=!` flag to force exit. On this release, `System.exit(0)` does not exit.

Filed #68 for timeouts.

**Comment by batsatt** [comment]
This needs to be fixed in Helidon: filed https://github.com/oracle/helidon/issues/1373
