### ISSUE TITLE
1.1.1 version of build tools is incompatible with Java 8 and therefore Helidon 1.4.x

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon-build-tools#71]
While testing the 1.4.2 release candidate the helidon-quickstart-se example failed when building with Dockerfile.native:

```
Caused by: java.lang.UnsupportedClassVersionError: 
io/helidon/build/maven/graal/GraalNativeMojo has been compiled by a more recent 
version of the Java Runtime (class file version 53.0), this version of the Java Runtime 
only recognizes class file versions up to 52.0
```

This appears to be because the build-tools plugin is now built targeting Java 9 (https://github.com/oracle/helidon-build-tools/blob/c982510aa6361a7be50cf0225328f9adaa954f17/pom.xml#L176)  but the 1.4.X Dockerfile.native uses the Java 8 version of GraalVM 19.3 (https://github.com/oracle/helidon/blob/3d76fd91215cab3ec7c9aae06bb5aee64a3a1872/examples/quickstarts/helidon-quickstart-se/Dockerfile.native#L18).

Options:

1. Change the build-tools plugin to target Java 8, but maybe that breaks the jlink image support.
2. Revert 1.4.x to use the previous version of build-tools, and abandon jlink image support in 1.4
3. Require Java 11+ when building native images (and jlink images) on 1.4. But this would break backwards compatibility with folks using a Java 8 version of graalvm.

Any of these options will require code changes and a rebuild.

**Comment by batsatt** [comment]
The `jlink-image` code requires Java 9. Since the `native-image` code won't work with 9, we need to back out the `jlink-image` integration in 1.4.2; see PR https://github.com/oracle/helidon/pull/1451
