### ISSUE TITLE
Failing tests on master since Helidon 3.0.0 release

### ISSUE THREAD

**Issue by tvallin** [oracle/helidon-build-tools#760]
Fix the tests

**Comment by romain-grecourt** [comment]
How comes the pipelines did not catch this ?
What's the error ?

**Comment by romain-grecourt** [comment]
Oh is this one of the tests that depends on https://helidon.io/cli-data ?

**Comment by tvallin** [comment]
Yes, after deploying Helidon 3.0.0 the test catch the issue because it pings https://helidon.io/cli-data and receive different response. I faced the same issue with functional tests.
