### ISSUE TITLE
Error:  The desired archetype does not exist (io.helidon.archetypes:helidon-quickstart-mp:3.0.0-SNAPSHOT)

### ISSUE THREAD

**Issue by wliusa** [oracle/helidon-build-tools#769]
Followed https://helidon.io/docs/v3/#/mp/guides/quickstart
Generate the Project
Generate the project sources using one (or both) of the Helidon Maven archetypes. The result is a simple project that shows the basics of configuring the WebServer and implementing basic routing rules.

Run the Maven archetype
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-mp \
    -DarchetypeVersion=3.0.0-SNAPSHOT \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-mp \
    -Dpackage=io.helidon.examples.quickstart.mp

Got error:
...
[INFO] Generating project in Batch mode
[INFO] Archetype repository not defined. Using the one from [io.helidon.archetypes:helidon-quickstart-mp:2.0.0-RC1] found in catalog remote
Downloading from snapshots: https://artifactory.oci.oraclecorp.com/libs-snapshot/io/helidon/archetypes/helidon-quickstart-mp/3.0.0-SNAPSHOT/maven-metadata.xml
Downloading from snapshots: https://artifactory.oci.oraclecorp.com/libs-snapshot/io/helidon/archetypes/helidon-quickstart-mp/3.0.0-SNAPSHOT/helidon-quickstart-mp-3.0.0-SNAPSHOT.pom
[WARNING] The POM for io.helidon.archetypes:helidon-quickstart-mp:jar:3.0.0-SNAPSHOT is missing, no dependency information available
Downloading from snapshots: https://artifactory.oci.oraclecorp.com/libs-snapshot/io/helidon/archetypes/helidon-quickstart-mp/3.0.0-SNAPSHOT/helidon-quickstart-mp-3.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.203 s
[INFO] Finished at: 2022-08-05T11:47:11-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (io.helidon.archetypes:helidon-quickstart-mp:3.0.0-SNAPSHOT) -> [Help 1]

**Comment by barchetta** [comment]
This is a bug in the Helidon documentatino. See https://github.com/oracle/helidon/issues/4685
