### ISSUE TITLE
ProjectStarter failure

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon-build-tools#777]
Steps to reproduce:

1. Use this project starter configuration https://helidon.io/starter/3.0.1?flavor=mp&step=4&app-type=custom&tracing=true 
2. Click on 'Application Type' step and change it to Quickstart
3. Click Download

ProjectStarter fails with this error:

````
Invocation error: Cannot set value, path=flavor.app-type.tracing, current={kind=EXTERNAL, DynamicValue{rawValue='true'}}, new={kind=PRESET, TypedValue{value='false', type=class java.lang.Boolean}}
````

**Comment by m0mus** [comment]
> @m0mus did you mean to type "true2" and not "true"?

No. It's a typo. I fixed the URL.

**Comment by romain-grecourt** [comment]
This is actually a UI issue, `tracing=true` should be invalidated when app-type is changed to quickstart.

**Comment by romain-grecourt** [comment]
Closing this issue as we will track the UI bug internally.
