### ISSUE TITLE
Project is not buildable

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon-build-tools#79]
Building on Windows. There are some failing tests (see attached build log for details). Project builds fine with `-DskipTests`.
[build.log](https://github.com/oracle/helidon-build-tools/files/4343263/build.log)

**Comment by romain-grecourt** [comment]
Probably a path escape or substitution issue. Can you provide a fix ?

**Comment by m0mus** [comment]
Unfortunately I have other things to do (like manage you folks). :)
We need to find someone from the team who can fix it.

**Comment by romain-grecourt** [comment]
Hmm, If you have cycles to mess with the site generator, I don't see why you can't fix this.
